spring:
  datasource:
    # TODO: these values can be inserted dynamically as well - probably not needed for this project
    url: jdbc:mysql://localhost:3306/e_learning_system?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  application:
    name: E-Learning-System

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8080